name: Zip Folders and Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Zip Folders
      run: |
        for dir in */; do
          zip -r "${dir%/}.zip" "$dir"
        done
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./*.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
